### ISSUE TITLE
Path doesn't return the correct value for path.0

### ISSUE THREAD

**Issue by omid** [actix/actix-web#1646]
In the latest Actix 3.0.0.beta3, Path doesn't return the correct value when I call path.0

## Steps to Reproduce (for bugs)
If you run the following code:
```
use actix_web::web::Path;
use actix_web::{web, App, HttpResponse, HttpServer, Responder};

async fn index2(path: Path<(String, i32)>) -> impl Responder {
    let param1 = path.0;
    let param2 = path.1;
    HttpResponse::Ok().body(format!("{}: {}", param1, param2))
}

#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| App::new().route("/test/{}/{}", web::get().to(index2)))
        .bind("127.0.0.1:8088")?
        .run()
        .await
}
```

It will return this error:
```
error[E0277]: `(std::string::String, i32)` doesn't implement `std::fmt::Display`
 --> src/main.rs:7:47
  |
7 |     HttpResponse::Ok().body(format!("{}: {}", param1, param2))
  |                                               ^^^^^^ `(std::string::String, i32)` cannot be formatted with the default formatter
  |
  = help: the trait `std::fmt::Display` is not implemented for `(std::string::String, i32)`
  = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
  = note: required by `std::fmt::Display::fmt`
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Sure I expect param.0 should be type String. Note that param.1 is i32!

## Your Environment
I'm using Rust 1.45.2 and the following Cargo.toml:

```
[package]
name = "app"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "3.0.0-beta.3"
actix-rt = "1.1.1"
```

And this code works fine with Actix 2.0.0.

**Comment by robjtede** [comment]
Check migration.md file. This is one of the breaking changes of v3.

**Comment by omid** [comment]
There are some ways to make it work.

Like this:
```
#[macro_use]
extern crate serde;

use actix_web::web::Path;
use actix_web::{web, App, HttpResponse, HttpServer, Responder};

#[derive(Deserialize)]
struct Params {
    s: String,
    i: i32,
}
async fn index2(path: Path<Params>) -> impl Responder {
    let param1 = &path.s;
    let param2 = path.i;
    HttpResponse::Ok().body(format!("{}: {}", param1, param2))
}

#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| App::new().route("/test/{}/{}", web::get().to(index2)))
        .bind("127.0.0.1:8088")?
        .run()
        .await
}
```

or something like this:
```
use actix_web::web::Path;
use actix_web::{web, App, HttpResponse, HttpServer, Responder};

async fn index2(path: Path<(String, i32)>) -> impl Responder {
    let inner_path = path.into_inner();
    let param1 = inner_path.0;
    let param2 = inner_path.1;
    HttpResponse::Ok().body(format!("{}: {}", param1, param2))
}

#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| App::new().route("/test/{}/{}", web::get().to(index2)))
        .bind("127.0.0.1:8088")?
        .run()
        .await
}
```

**Comment by omid** [comment]
Wow, you are too fast :D 
Thanks @robjtede
