### ISSUE TITLE
need to push a new version on crates that works with actix 0.4

### ISSUE THREAD

**Issue by guanqun** [actix/actix-web#41]
Looks like the latest interface change in `Handler` cause the failure of 0.2.1 of actix-web. You need to push a new version to crates. :)

**Comment by fafhrd91** [comment]
I do not want to spend time on 0.2 branch. 0.3 is the future and it is completely different

**Comment by guanqun** [comment]
Understood. But the current top two versions of actix and actix-web don't match, it had compilation errors.

**Comment by mentalbrew** [comment]
h2 has been published to crates.io today. Perhaps now would be a good time to push a new version of actix-web?

**Comment by fafhrd91** [comment]
Awesome! Will do new release soon.

I need to think what to do with flate2 dependency and cookies-rs

**Comment by fafhrd91** [comment]
actix-web 0.3.0 is released
