### ISSUE TITLE
the trait bound `rand_hc::Hc128Rng: rand_core::SeedableRng` is not satisfied

### ISSUE THREAD

**Issue by Turbo87** [actix/actix-web#620]
When updating from actix 0.7.7 to 0.7.8 (see https://github.com/Turbo87/ogn-web-gateway/pull/89), I'm seeing the following errors on CI:

```
error[E0277]: the trait bound `rand_hc::Hc128Rng: rand_core::SeedableRng` is not satisfied
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.6.1/src/rngs/std.rs:51:6
   |
51 | impl SeedableRng for StdRng {
   |      ^^^^^^^^^^^ the trait `rand_core::SeedableRng` is not implemented for `rand_hc::Hc128Rng`
error[E0277]: the trait bound `rand_chacha::ChaChaRng: rand_core::SeedableRng` is not satisfied
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.6.1/src/deprecated.rs:141:6
    |
141 | impl SeedableRng for ChaChaRng {
    |      ^^^^^^^^^^^ the trait `rand_core::SeedableRng` is not implemented for `rand_chacha::ChaChaRng`
error[E0277]: the trait bound `rand_hc::Hc128Rng: rand_core::SeedableRng` is not satisfied
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.6.1/src/deprecated.rs:198:6
    |
198 | impl SeedableRng for Hc128Rng {
    |      ^^^^^^^^^^^ the trait `rand_core::SeedableRng` is not implemented for `rand_hc::Hc128Rng`
error[E0277]: the trait bound `rand_xorshift::XorShiftRng: rand_core::SeedableRng` is not satisfied
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.6.1/src/deprecated.rs:239:6
    |
239 | impl SeedableRng for XorShiftRng {
    |      ^^^^^^^^^^^ the trait `rand_core::SeedableRng` is not implemented for `rand_xorshift::XorShiftRng`
```
(see https://travis-ci.org/Turbo87/ogn-web-gateway/jobs/465814940)

**Comment by Turbo87** [comment]
why did you transfer the issue to `actix-web`? I was updating `actix`, not `actix-web` 🤔

**Comment by DoumanAsh** [comment]
Oh... I see, only `actix-web` uses `rand` directly so I thought you were updating both.
But if it is only `actix` then it is not `actix` issue at all
