### ISSUE TITLE
Actix-web v4.0.0-beta.19 doesn't work with actix-router v0.5.0-rc.1 (or rc.2)

### ISSUE THREAD

**Issue by Thomasdezeeuw** [actix/actix-web#2603]
## Expected Behavior

Actix-web v4.0.0-beta.19 doesn't work with actix-router v0.5.0-rc.1 (or rc.2), downgrading to beta.4 fixes it.

## Current Behavior

Error:

```
error[E0107]: this trait takes 0 generic arguments but 1 generic argument was supplied
   --> /Users/thomas/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.19/src/service.rs:310:6
    |
310 | impl Resource<Url> for ServiceRequest {
    |      ^^^^^^^^----- help: remove these generics
    |      |
    |      expected 0 generic arguments
    |
note: trait defined here, with 0 generic parameters
   --> /Users/thomas/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-router-0.5.0-rc.1/src/resource_path.rs:5:11
    |
5   | pub trait Resource {
    |           ^^^^^^^^

error[E0046]: not all trait items implemented, missing: `Path`
   --> /Users/thomas/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.0.0-beta.19/src/service.rs:310:1
    |
310 | impl Resource<Url> for ServiceRequest {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `Path` in implementation
    |
    = help: implement the missing item: `type Path = Type;`
```

## Possible Solution

It think it's already fixed on master, so a release should fix it.

## Steps to Reproduce (for bugs)

1. Use Actix-web v4.0.0-beta.19
2. actix-router v0.5.0-rc.1 (or rc2)
3. `cargo check`

**Comment by robjtede** [comment]
actix-web v4 beta 21 is compatible with the newest router crate
