### ISSUE TITLE
`actix-files v0.6.0-beta.4` fails to compile with `actix-web v4.0.0-beta.6`

### ISSUE THREAD

**Issue by ghost** [actix/actix-web#2185]
## Expected Behavior
The `actix-files` crate should not fail to compile.

## Current Behavior
The `actix-files` crate fails to compile.
```rust
error[E0053]: method `error_response` has an incompatible type for trait
  --> /Users/emilsayahi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-files-0.6.0-beta.4/src/error.rs:19:33
   |
19 |     fn error_response(&self) -> HttpResponse {
   |                                 ^^^^^^^^^^^^
   |                                 |
   |                                 expected struct `BaseHttpResponse`, found struct `actix_web::HttpResponse`
   |                                 help: change the output type to match the trait: `BaseHttpResponse<actix_web::dev::Body>`
   |
   = note: expected fn pointer `fn(&FilesError) -> BaseHttpResponse<actix_web::dev::Body>`
              found fn pointer `fn(&FilesError) -> actix_web::HttpResponse`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0053`.
error: could not compile `actix-files`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

## Possible Solution
Change the output type of `fn error_response(&self)` in `actix-files` to match the trait `BaseHttpResponse<actix_web::dev::Body>`

## Steps to Reproduce (for bugs)
1. Create a Rust project with `actix-files v0.6.0-beta.4` and `actix-web v4.0.0-beta.6` somewhere in the dependency tree
2. Attempt to build said project

## Context
This has led to build failures for [my project, Dokkoo](https://github.com/Dirout/dokkoo), across [all its supported platforms](https://github.com/Dirout/dokkoo/discussions/70).

## Your Environment
Tested on `aarch64-unknown-linux-gnu`, `x86_64-apple-darwin`, `x86_64-pc-windows-msvc`, `x86_64-unknown-linux-gnu`, and `aarch64-apple-darwin`.

* Rust Version (I.e, output of `rustc -V`): `rustc 1.53.0-nightly (16bf626a3 2021-04-14)`
* Actix Web Version: `v4.0.0-beta.6`

**Comment by robjtede** [comment]
workaround is to pin actix-http `=v3.0.0-beta.5` and actix-web `=v4.0.0-beta.5`

**Comment by ghost** [comment]
@robjtede 
```rust
error[E0432]: unresolved import `actix_service::pipeline_factory`
  --> /Users/emilsayahi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0-beta.5/src/service.rs:13:21
   |
13 | use actix_service::{pipeline_factory, IntoServiceFactory, Service, ServiceFactory};
   |                     ^^^^^^^^^^^^^^^^ no `pipeline_factory` in the root

error[E0432]: unresolved import `actix_service::pipeline_factory`
 --> /Users/emilsayahi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0-beta.5/src/h1/service.rs:8:21
  |
8 | use actix_service::{pipeline_factory, IntoServiceFactory, Service, ServiceFactory};
  |                     ^^^^^^^^^^^^^^^^ no `pipeline_factory` in the root

error[E0432]: unresolved import `actix_service::pipeline_factory`
  --> /Users/emilsayahi/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-3.0.0-beta.5/src/h2/service.rs:10:29
   |
10 |     fn_factory, fn_service, pipeline_factory, IntoServiceFactory, Service,
   |                             ^^^^^^^^^^^^^^^^ no `pipeline_factory` in the root

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0432`.
error: could not compile `actix-http`
```

Using,
```toml
[dependencies]
actix-files = "0.6.0-beta.4"
actix-http = "=3.0.0-beta.5"
actix-rt = "2.2.0"
actix-web = "=4.0.0-beta.5"
```

**Comment by ghost** [comment]
I've found a workaround: pinning `actix-http v3.0.0-beta.5`, `actix-service v2.0.0-beta.5`, and `actix-web v4.0.0-beta.5`.
```toml
[dependencies]
actix-files = "0.6.0-beta.4"
actix-http = "=3.0.0-beta.5"
actix-rt = "2.2.0"
actix-service = "=2.0.0-beta.5"
actix-web = "=4.0.0-beta.5"
```

**Comment by hoodie** [comment]
<off-topic>
Are these long lived beta releases really necessary? especially the fact that actix consists of several separate crates and they are all in different stages of beta for weeks makes it a bit hard to try out new stuff. How do you test this? Would it make sense to pull everything together (mono-repo style) and release everything at once (maybe even x.0.0-beta.13) but at least have everthing match. I'm just asking since I'd like to try out new actix versions too from time to time, but then spend a lot of time mixing and matching versions of all the deps until I find something that compiles together.

thanks

**Comment by warriorsfly** [comment]
`actix-web-actors = "4.0.0-beta.4"` the same

**Comment by tibinthomas** [comment]
Any updates

**Comment by robjtede** [comment]
actix-web v4.0.0-beta.7 is released as well as updates for other crates in -web repo

-extras crates to follow
