### ISSUE TITLE
actix-web v4.2.0's actix-http dependency is not specific enough

### ISSUE THREAD

**Issue by caizixian** [actix/actix-web#2869]
# *Update: The issue has been fixed in v4.2.1, please update your actix-web version.* 

## Expected Behavior
`actix-web` v4.2.0 successfully build, as long as its transitive dependencies all satisfy the version constraints.

## Current Behavior
`actix-web` v4.2.0 doesn't build with actix-http v3.2.0 despite the actix-http version satisfies the constraint.

https://github.com/actix/actix-web/blob/7767cf30710ec2a8666b0c9e6f578aa590038a54/actix-web/Cargo.toml#L74

## Possible Solution
Change `Cargo.toml` in `actix-web` to point to `actix-http` 3.2.2+.

## Steps to Reproduce (for bugs)
Create a repo with `actix-web` pinned to `v4.2.0` and `actix-http` `v3.2.0`.
`cargo build` fails with the following.

```console
   Compiling actix-web v4.2.0
error[E0277]: the trait bound `actix_http::header::ExtendedValue: std::cmp::Eq` is not satisfied
   --> $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-4.2.0/src/http/header/content_disposition.rs:99:17
    |
82  | #[derive(Clone, Debug, PartialEq, Eq)]
    |                                   -- in this derive macro expansion
...
99  |     FilenameExt(ExtendedValue),
    |                 ^^^^^^^^^^^^^ the trait `std::cmp::Eq` is not implemented for `actix_http::header::ExtendedValue`
    |
note: required by a bound in `AssertParamIsEq`
   --> $HOME/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/cmp.rs:317:31
    |
317 | pub struct AssertParamIsEq<T: Eq + ?Sized> {
    |                               ^^ required by this bound in `AssertParamIsEq`
    = note: this error originates in the derive macro `Eq` (in Nightly builds, run with -Z macro-backtrace for more info)
```

## Context
The repo has `Cargo.lock`. Dependabot bumps the actix-web, which causes the build to fail because `actix-http` is not new enough.

## Your Environment
- Rust Version (I.e, output of `rustc -V`): `rustc 1.63.0 (4b91a6ea7 2022-08-08)`
- Actix Web Version: 4.2.0

**Comment by GyomeGyd** [comment]
Same problem here

**Comment by ilka-schulz** [comment]
same problem here with today's current nightly:
```text
rustc 1.65.0-nightly (59e7a308e 2022-09-11)
cargo 1.65.0-nightly (646e9a0b9 2022-09-02)
```

**Comment by naturalfreak** [comment]
Same

**Comment by robjtede** [comment]
`actix-web` v4.2.1 is released and should fix this issue.

Run `cargo update` and `cargo tree -i actix-http` to verify which version is being used.

Apologies for the oversight.

**Comment by JohnTitor** [comment]
@robjtede I've pinned this to let users know that the issue has been fixed in the latest version, feel free to unpin once you assume most users update their deps :)

**Comment by amitu** [comment]
With 4.2.1 I am still facing incompatibility with zip=0.6 as mentioned in #2872. They seems to have fixed the issue in Git but not yet created a release, so using `zip = { git = "https://github.com/zip-rs/zip" }` resolves the issue.

**Comment by JohnTitor** [comment]
> With 4.2.1 I am still facing incompatibility with zip=0.6 as mentioned in #2872. They seems to have fixed the issue in Git but not yet created a release, so using `zip = { git = "https://github.com/zip-rs/zip" }` resolves the issue.

Isn't that an issue around zstd? If so, it's completely unrelated to this issue.

**Comment by lebe-dev** [comment]
> > With 4.2.1 I am still facing incompatibility with zip=0.6 as mentioned in #2872. They seems to have fixed the issue in Git but not yet created a release, so using `zip = { git = "https://github.com/zip-rs/zip" }` resolves the issue.
> 
> Isn't that an issue around zstd? If so, it's completely unrelated to this issue.

yes, issue with zstd

**Comment by mozhou-tech** [comment]
Depends on my test, issue still exists in zip=0.6.0 and after.
downgrade zip=0.5.13 to solve this issue.
